create_cluster 1
show_details_cluster 1
delete_cluster 1
remove_nodes_from_cluster 1
shutoff_nodes 1
start_nodes 1
reboot_nodes 1
open_openstack 1
close_openstack 1
add_nodes_to_cluster 1
open_cmd 1
add_instance 1
remove_instance 1
go_to_instance 1
back_home 1
