create_cluster 1
show_details_cluster 1
delete_cluster 1
remove_nodes_from_cluster 1
shutoff_nodes 1
start_nodes 1
reboot_nodes 1
open_openstack 1
close_openstack 1
add_nodes_to_cluster 1
add_instance 1
remove_instance 1
go_to_instance 1
back_home 1
compnode1crash 1
compnode2crash 1
compnode1netwisol 1
compnode2netwisol 1
compnode1hang 1
compnode2hang 1
contrnode1crash 1
contrnode2crash 1
contrnode1netwisol 1
contrnode2netwisol 1
contrnode1hang 1
contrnode2hang 1
vm-crash 1
vm-oshanged 1
