open_openstack 1 
create_cluster 1 
add_nodes_to_cluster 1 
add_instance 1 
compnode1crash 1 
compnode2crash 1 
compnode1netwisol 1 
compnode2netwisol 1 
compnode1hang 1 
compnode2hang 1 
close_openstack 1 
open_openstack 1 
vm-oshanged 1 
vm-crash 1 
vm-network 1 
go_to_instance 1 
remove_instance 1 
back_home 1 
remove_nodes_from_cluster 1 
delete_cluster 1 
close_openstack 1 
